DROP TABLE IF EXISTS Evidence CASCADE;
DROP TABLE IF EXISTS Suspect CASCADE;
DROP TABLE IF EXISTS Evidence_facts CASCADE;
DROP TABLE IF EXISTS Suspect_facts CASCADE;
DROP TABLE IF EXISTS Suspect_observations CASCADE;
DROP TYPE IF EXISTS observation_type CASCADE;
